### PR TITLE
Improve compliance with RFC 7946

### PR DESCRIPTION
**Pull request by chris48s**
Based on discussion in #21

* Wind outer rings counterclockwise and inner rings clockwise
* Prevent values other than string or number in id field
* Convert but log a warning if SRID is not 4326
* Add tests to formalise this behaviour

### CODE REVIEW

**Comment by chris48s** [comment]
3f12cf2 isn't strictly related to this PR but was needed to get the build running. I expect the Chrome dependency or Travis environment has changed since a build was last run. Now that the build is running, it looks like there are some failures I need to address which I did not encounter locally (strangely, the linter seems to enforce different rules under node 6 than node 8, which I did not expect).

Let me look at these and update the PR before review.

**Comment by chris48s** [comment]
I've spent a bit of time on it and I fear this PR may get bogged down in trying to fix unrelated problems.

I've opened #23 just to demonstrate that the same failures are present even if I don't make any changes to the library code or tests.

If you want me to re-indent all the test fixtures, that's fine. If you want to change your linter config I'll leave it with you. Either way it is probably best to that it in another PR and then rebase this on to it (particularly if doing a large number of white space changes as it will add a lot of unrelated noise to this PR and make it hard to review).

I'm not sure how to fix the browser tests but as you can see from the build on #23 it doesn't seem to be anything I have changed in this PR that is stopping it from running.

Either way, lets park review of this PR until there is a passing build on master that I can rebase it on to.

**Comment by jgravois** [comment]
the dangers of using `"semistandard": "*"` 😠...

i've merged the fix into `master`. sorry to send you on a goose chase.

**Comment by chris48s** [comment]
No probs. I've rebased my changes and the build is now passing.
I'll pick up any comments tomorrow :)

**Comment by jgravois** [comment]
solid contribution. thank you @chris48s!

**Pull request merged**
