### PR TITLE
Added TypeScript definitions

### PR DESCRIPTION
**Pull request by JeffJacobson**
Added TypeScript definitions for this module. :package:

### CODE REVIEW

**Comment by jgravois** [comment]
for this last one how do you feel going about the [`typings/registry`](https://github.com/typings/registry) route? i'd like to get familiar with that workflow as well.

**Comment by JeffJacobson** [comment]
OK, I'll try adding them via [DefinitelyTyped]. This is now the recommended way to publish types for TypeScript 2.x when not bundling the types into the library itself.

[DefinitelyTyped]:https://github.com/JeffJacobson/DefinitelyTyped/blob/types-2.0/README.md

**Comment by JeffJacobson** [comment]
I've made a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13145) in DefinitelyTyped for `arcgis-to-geojson`.

**Comment by jgravois** [comment]
awesome @JeffJacobson! thanks so much!

**Comment by jgravois** [comment]
i added a link and shoutout to the README in 1f2957f.  

thanks again for this contribution!

**Pull request closed without merging**
